[project]
name = "boilerplate_package"
version = "0.1.0"
description = "A Python boilerplate made by mediocreDev"
readme = "README.md"
authors = [
    { name = "Americio Hoag", email = "trusted7536@gmail.com" }
]
requires-python = ">=3.13.5"
dependencies = [
    "python-dotenv>=1.1.1",
]

[project.scripts]
boilerplate = "boilerplate_package:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
